apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/getting-started

deploy:
  kubectl:
    manifests:
      - k8s-*

profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: kubecon-eu-skaffold-demo
