[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/moby/moby"
  revision = "e1f98e8ab3cb5ae5c0f452cdd81ac4a954279e62"

[[override]]
  name = "github.com/docker/docker"
  revision = "e1f98e8ab3cb5ae5c0f452cdd81ac4a954279e62"

[[constraint]]
  name = "github.com/docker/cli"
  revision = "b5df4f69db84a16479f16a4bc789d9b5664a47b9"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v9.1.0"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  name = "google.golang.org/api"
  revision = "ff7b961889714494dc1feb2e8359298cbd20e5e3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "v4.3.0"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "7da7957aee21f95e68545e1ae235654daec23c89"


[[constraint]]
  branch = "master"
  name = "github.com/containerbuilding/cbi"
