apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/getting-started
    bazel:
      target: //:skaffold_example.tar

deploy:
  kubectl:
    manifests:
      - k8s-*
