apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/getting-started
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
