apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: hexagons
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: hexagons
      tier: db
  template:
    metadata:
      labels:
        app: hexagons
        tier: db
    spec:
      containers:
      - name: db
        image: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-db
