apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  ports:
  - port: 80
    name: http
  type: LoadBalancer
  selector:
    app: hexagons
    tier: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: hexagons
      tier: ui
  template:
    metadata:
      labels:
        app: hexagons
        tier: ui
    spec:
      containers:
      - name: ui
        image: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-ui
      - name: api
        image: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-api
