apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-ui
    workspace: ./ui
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-api
    workspace: ./api
  - imageName: eu.gcr.io/kubecon-eu-skaffold-demo/hexagons-db
    workspace: ./db

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: kubecon-eu-skaffold-demo
